version: "2.1"

services:
  front:
    container_name: ${PROJECT_NAME}_front
    build:
      context: ./PerformaFront
      dockerfile: Dockerfile-dev
    volumes:
      - "./PerformaFront:/usr/src/app"
      - "./PerformaFront/dist:/usr/src/app/dist"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: 5858
      BACKEND_URI: "localhost:${NGINX_PORT}/graphql"
    ports:
      - 5858:5858
    networks:
      - performa_network

  back:
    container_name: ${PROJECT_NAME}_back
    build:
      context: ./PerformaBack
      dockerfile: Dockerfile-dev
    volumes:
      - "./PerformaBack:/usr/src/app"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: 3000
      MONGO_URI: "mongodb://mongo:${MONGO_PORT}/${MONGO_DB_NAME}"
    ports:
      - 3000:3000
    networks:
      - performa_network

  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - performa_network

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./PerformaFront/dist:/var/www/html/"
      - "./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - performa_network
    depends_on:
      - front


networks:
  performa_network:
    driver: bridge
