version: "2.1"

services:
  ui:
    container_name: ${PROJECT_NAME}_ui
    build:
      context: ./PerformaFront
      dockerfile: Dockerfile-dev
    volumes:
      - "./PerformaFront/src:/usr/src/app/src"
      - "./PerformaCommon:/usr/src/app/src/PerformaCommon"
      - "./PerformaFront/public:/usr/src/app/public"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $UI_PORT
      BACKEND_URI: "localhost:${NGINX_PORT}/graphql"
    ports:
      - "${UI_PORT}:${UI_PORT}"

  gql:
    container_name: ${PROJECT_NAME}_gql
    build:
      context: ./PerformaBack
      dockerfile: Dockerfile-dev
    volumes:
      - "./PerformaBack/src:/usr/src/app/src"
      - "./PerformaCommon:/usr/src/app/src/PerformaCommon"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $GRAPH_PORT
      MONGO_URI: "mongodb://mongo:${MONGO_PORT}/${MONGO_DB_NAME}"
      SESSION_SECRET: "ksbfysdfsnhdfsyufsjhflsh98fdusf"
      RTMP_IINER_URL: "http://127.0.0.1:1935/hls-live/"
    ports:
      - "${GRAPH_PORT}:${GRAPH_PORT}"

  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/mongo:/data/db

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: itaywol/rtmp-nginx:latest
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_STREAMING_PORT}:1935"
    volumes:
      - "./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/streaming.conf:/etc/nginx/streaming.conf"
    depends_on:
      - ui

