version: "2.1"

services:
  ui:
    container_name: ${PROJECT_NAME}_ui
    build:
      context: ./PerformaFront
      dockerfile: Dockerfile-dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./PerformaFront/src:/usr/src/app/src"
      - "./PerformaCommon:/usr/src/app/src/PerformaCommon"
      - "./PerformaFront/public:/usr/src/app/public"
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $UI_PORT
      BACKEND_URI: "localhost:${NGINX_PORT}/"
    ports:
      - "${UI_PORT}:${UI_PORT}"

  back:
    container_name: ${PROJECT_NAME}_back
    build:
      context: ./PerformaBack
      dockerfile: Dockerfile-dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./PerformaBack/src:/usr/src/app/src"
      - "./PerformaCommon:/usr/src/app/src/PerformaCommon"
    command: npm run start:debug
    environment:
      NODE_ENV: $NODE_ENV
      PORT: $BACK_PORT
      PORT_WS: $BACK_WS_PORT
      MONGO_URI: "mongodb://mongo:${MONGO_PORT}/${MONGO_DB_NAME}"
      EXPRESS_CORS: '*'
      SESSION_SECRET: "ksbfysdfsnhdfsyufsjhflsh98fdusf"
      SESSION_COOKIE_NAME: "performa_auth"
      SESSION_COOKIE_MAX_AGE: "2592000000"
      SESSION_MONGO_COLLECTION_NAME: "authSessions"
      PUBLIC_DOMAIN: "localhost"
      RTMP_INNER_URL: "rtmp://127.0.0.1:1935/encode/"
      WATCHING_STREAM_REQUIRES_AUTH: "false"
      STREAM_KEYS_PREFIX: "Perform"
      GOOGLE_STORAGE_BUCKET_NAME: "performa_dev"
      GOOGLE_PROJECT_ID: "performa-273910"
      BRAINTREE_PUBLIC_KEY: "z4hpgxgxnzhvy5qm"
      BRAINTREE_PRIVATE_KEY: "03e2d4cb2abba13648ed7d6e71cc70cb"
      BRAINTREE_MERCHANT_ID: "ddp5g7d4yw685jpx"
      PAYPAL_CLIENT_ID: "AX99iMVMS7THAEaVnN3z2FZuqBIjoFP4AE1JZzHdLPfa_aS8nSpFEiLUP1yjkpiAk5MfLvxTozvcxqUb"
      PAYPAL_CLIENT_SECRET: "EAVw6EH8s4mdJguHOMsrLXHF9oFHHR2I3243UmI65IOYTecl1vffqKya0tYf697KYOZxduNDalvKDBTh"
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
      - "${BACK_WS_PORT}:${BACK_WS_PORT}"
      - "9229:9229"

  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/mongo:/data/db

  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: itaywol/nginx-rtmp-dash-ffmpeg
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_STREAMING_PORT}:1935"
    volumes:
      - "./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/streaming.conf:/etc/nginx/streaming.conf"
    depends_on:
      - ui

